# Generated by Django 4.0.5 on 2022-06-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_desc', models.CharField(max_length=1000)),
                ('pub_date', models.DateField()),
                ('blog_imgs', models.ImageField(upload_to='')),
            ],
        ),
    ]
