# Generated by Django 4.0.5 on 2022-06-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_star',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_desc',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
