# Generated by Django 4.0.5 on 2022-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_blog_star_alter_post_blog_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
