# Generated by Django 4.0.5 on 2022-06-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_newfeatured_featured_delete_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_featured',
            field=models.BooleanField(default=False),
        ),
    ]
