# Generated by Django 4.0.5 on 2022-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_category_delete_featured_alter_post_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_title',
            field=models.CharField(max_length=100),
        ),
    ]
