# Generated by Django 4.0.5 on 2022-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_category_cat_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_featured',
            new_name='blog_feature',
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
