# Generated by Django 4.0.5 on 2022-06-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_featured_rename_blog_feature_post_blog_featured'),
    ]

    operations = [
        migrations.DeleteModel(
            name='featured',
        ),
    ]
