# Generated by Django 4.0.5 on 2022-06-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='c_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
